// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/App.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.STRING;

public final class AndroidAppNotificationData extends Message {

  public static final Integer DEFAULT_VERSIONCODE = 0;
  public static final String DEFAULT_ASSETID = "";

  @ProtoField(tag = 1, type = INT32)
  public final Integer versionCode;

  @ProtoField(tag = 2, type = STRING)
  public final String assetId;

  public AndroidAppNotificationData(Integer versionCode, String assetId) {
    this.versionCode = versionCode;
    this.assetId = assetId;
  }

  private AndroidAppNotificationData(Builder builder) {
    this(builder.versionCode, builder.assetId);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof AndroidAppNotificationData)) return false;
    AndroidAppNotificationData o = (AndroidAppNotificationData) other;
    return equals(versionCode, o.versionCode)
        && equals(assetId, o.assetId);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = versionCode != null ? versionCode.hashCode() : 0;
      result = result * 37 + (assetId != null ? assetId.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<AndroidAppNotificationData> {

    public Integer versionCode;
    public String assetId;

    public Builder() {
    }

    public Builder(AndroidAppNotificationData message) {
      super(message);
      if (message == null) return;
      this.versionCode = message.versionCode;
      this.assetId = message.assetId;
    }

    public Builder versionCode(Integer versionCode) {
      this.versionCode = versionCode;
      return this;
    }

    public Builder assetId(String assetId) {
      this.assetId = assetId;
      return this;
    }

    @Override
    public AndroidAppNotificationData build() {
      return new AndroidAppNotificationData(this);
    }
  }
}
