// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Documents.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

public final class BulkDetailsEntry extends Message {

  @ProtoField(tag = 1)
  public final DocV2 doc;

  public BulkDetailsEntry(DocV2 doc) {
    this.doc = doc;
  }

  private BulkDetailsEntry(Builder builder) {
    this(builder.doc);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof BulkDetailsEntry)) return false;
    return equals(doc, ((BulkDetailsEntry) other).doc);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = doc != null ? doc.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<BulkDetailsEntry> {

    public DocV2 doc;

    public Builder() {
    }

    public Builder(BulkDetailsEntry message) {
      super(message);
      if (message == null) return;
      this.doc = message.doc;
    }

    public Builder doc(DocV2 doc) {
      this.doc = doc;
      return this;
    }

    @Override
    public BulkDetailsEntry build() {
      return new BulkDetailsEntry(this);
    }
  }
}
