// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Carrier.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.STRING;

public final class CarrierBillingInstrumentStatus extends Message {

  public static final Boolean DEFAULT_ASSOCIATIONREQUIRED = false;
  public static final Boolean DEFAULT_PASSWORDREQUIRED = false;
  public static final Integer DEFAULT_APIVERSION = 0;
  public static final String DEFAULT_NAME = "";

  @ProtoField(tag = 1)
  public final CarrierTos carrierTos;

  @ProtoField(tag = 2, type = BOOL)
  public final Boolean associationRequired;

  @ProtoField(tag = 3, type = BOOL)
  public final Boolean passwordRequired;

  @ProtoField(tag = 4)
  public final PasswordPrompt carrierPasswordPrompt;

  @ProtoField(tag = 5, type = INT32)
  public final Integer apiVersion;

  @ProtoField(tag = 6, type = STRING)
  public final String name;

  public CarrierBillingInstrumentStatus(CarrierTos carrierTos, Boolean associationRequired, Boolean passwordRequired, PasswordPrompt carrierPasswordPrompt, Integer apiVersion, String name) {
    this.carrierTos = carrierTos;
    this.associationRequired = associationRequired;
    this.passwordRequired = passwordRequired;
    this.carrierPasswordPrompt = carrierPasswordPrompt;
    this.apiVersion = apiVersion;
    this.name = name;
  }

  private CarrierBillingInstrumentStatus(Builder builder) {
    this(builder.carrierTos, builder.associationRequired, builder.passwordRequired, builder.carrierPasswordPrompt, builder.apiVersion, builder.name);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof CarrierBillingInstrumentStatus)) return false;
    CarrierBillingInstrumentStatus o = (CarrierBillingInstrumentStatus) other;
    return equals(carrierTos, o.carrierTos)
        && equals(associationRequired, o.associationRequired)
        && equals(passwordRequired, o.passwordRequired)
        && equals(carrierPasswordPrompt, o.carrierPasswordPrompt)
        && equals(apiVersion, o.apiVersion)
        && equals(name, o.name);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = carrierTos != null ? carrierTos.hashCode() : 0;
      result = result * 37 + (associationRequired != null ? associationRequired.hashCode() : 0);
      result = result * 37 + (passwordRequired != null ? passwordRequired.hashCode() : 0);
      result = result * 37 + (carrierPasswordPrompt != null ? carrierPasswordPrompt.hashCode() : 0);
      result = result * 37 + (apiVersion != null ? apiVersion.hashCode() : 0);
      result = result * 37 + (name != null ? name.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<CarrierBillingInstrumentStatus> {

    public CarrierTos carrierTos;
    public Boolean associationRequired;
    public Boolean passwordRequired;
    public PasswordPrompt carrierPasswordPrompt;
    public Integer apiVersion;
    public String name;

    public Builder() {
    }

    public Builder(CarrierBillingInstrumentStatus message) {
      super(message);
      if (message == null) return;
      this.carrierTos = message.carrierTos;
      this.associationRequired = message.associationRequired;
      this.passwordRequired = message.passwordRequired;
      this.carrierPasswordPrompt = message.carrierPasswordPrompt;
      this.apiVersion = message.apiVersion;
      this.name = message.name;
    }

    public Builder carrierTos(CarrierTos carrierTos) {
      this.carrierTos = carrierTos;
      return this;
    }

    public Builder associationRequired(Boolean associationRequired) {
      this.associationRequired = associationRequired;
      return this;
    }

    public Builder passwordRequired(Boolean passwordRequired) {
      this.passwordRequired = passwordRequired;
      return this;
    }

    public Builder carrierPasswordPrompt(PasswordPrompt carrierPasswordPrompt) {
      this.carrierPasswordPrompt = carrierPasswordPrompt;
      return this;
    }

    public Builder apiVersion(Integer apiVersion) {
      this.apiVersion = apiVersion;
      return this;
    }

    public Builder name(String name) {
      this.name = name;
      return this;
    }

    @Override
    public CarrierBillingInstrumentStatus build() {
      return new CarrierBillingInstrumentStatus(this);
    }
  }
}
