// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Notifications.proto
package com.google.play.proto;

import com.squareup.wire.Message;

public final class CheckForNotificationsResponseProto extends Message {

  public CheckForNotificationsResponseProto() {
  }

  private CheckForNotificationsResponseProto(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof CheckForNotificationsResponseProto;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<CheckForNotificationsResponseProto> {

    public Builder() {
    }

    public Builder(CheckForNotificationsResponseProto message) {
      super(message);
    }

    @Override
    public CheckForNotificationsResponseProto build() {
      return new CheckForNotificationsResponseProto(this);
    }
  }
}
