// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Unsorted.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;

public final class CheckLicenseRequestProto extends Message {

  public static final String DEFAULT_PACKAGENAME = "";
  public static final Integer DEFAULT_VERSIONCODE = 0;
  public static final Long DEFAULT_NONCE = 0L;

  @ProtoField(tag = 1, type = STRING)
  public final String packageName;

  @ProtoField(tag = 2, type = INT32)
  public final Integer versionCode;

  @ProtoField(tag = 3, type = INT64)
  public final Long nonce;

  public CheckLicenseRequestProto(String packageName, Integer versionCode, Long nonce) {
    this.packageName = packageName;
    this.versionCode = versionCode;
    this.nonce = nonce;
  }

  private CheckLicenseRequestProto(Builder builder) {
    this(builder.packageName, builder.versionCode, builder.nonce);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof CheckLicenseRequestProto)) return false;
    CheckLicenseRequestProto o = (CheckLicenseRequestProto) other;
    return equals(packageName, o.packageName)
        && equals(versionCode, o.versionCode)
        && equals(nonce, o.nonce);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = packageName != null ? packageName.hashCode() : 0;
      result = result * 37 + (versionCode != null ? versionCode.hashCode() : 0);
      result = result * 37 + (nonce != null ? nonce.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<CheckLicenseRequestProto> {

    public String packageName;
    public Integer versionCode;
    public Long nonce;

    public Builder() {
    }

    public Builder(CheckLicenseRequestProto message) {
      super(message);
      if (message == null) return;
      this.packageName = message.packageName;
      this.versionCode = message.versionCode;
      this.nonce = message.nonce;
    }

    public Builder packageName(String packageName) {
      this.packageName = packageName;
      return this;
    }

    public Builder versionCode(Integer versionCode) {
      this.versionCode = versionCode;
      return this;
    }

    public Builder nonce(Long nonce) {
      this.nonce = nonce;
      return this;
    }

    @Override
    public CheckLicenseRequestProto build() {
      return new CheckLicenseRequestProto(this);
    }
  }
}
