// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Documents.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class ContainerWithBanner extends Message {

  public static final String DEFAULT_COLORTHEMEARGB = "";

  @ProtoField(tag = 1, type = STRING)
  public final String colorThemeArgb;

  public ContainerWithBanner(String colorThemeArgb) {
    this.colorThemeArgb = colorThemeArgb;
  }

  private ContainerWithBanner(Builder builder) {
    this(builder.colorThemeArgb);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ContainerWithBanner)) return false;
    return equals(colorThemeArgb, ((ContainerWithBanner) other).colorThemeArgb);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = colorThemeArgb != null ? colorThemeArgb.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<ContainerWithBanner> {

    public String colorThemeArgb;

    public Builder() {
    }

    public Builder(ContainerWithBanner message) {
      super(message);
      if (message == null) return;
      this.colorThemeArgb = message.colorThemeArgb;
    }

    public Builder colorThemeArgb(String colorThemeArgb) {
      this.colorThemeArgb = colorThemeArgb;
      return this;
    }

    @Override
    public ContainerWithBanner build() {
      return new ContainerWithBanner(this);
    }
  }
}
