// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Documents.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

public final class DetailsResponse extends Message {

  /**
   * optional DocV1 docV1 = 1;
   * optional string analyticsCookie = 2;
   * optional Review userReview = 3;
   */
  @ProtoField(tag = 4)
  public final DocV2 docV2;

  public DetailsResponse(DocV2 docV2) {
    this.docV2 = docV2;
  }

  private DetailsResponse(Builder builder) {
    this(builder.docV2);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof DetailsResponse)) return false;
    return equals(docV2, ((DetailsResponse) other).docV2);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = docV2 != null ? docV2.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<DetailsResponse> {

    public DocV2 docV2;

    public Builder() {
    }

    public Builder(DetailsResponse message) {
      super(message);
      if (message == null) return;
      this.docV2 = message.docV2;
    }

    /**
     * optional DocV1 docV1 = 1;
     * optional string analyticsCookie = 2;
     * optional Review userReview = 3;
     */
    public Builder docV2(DocV2 docV2) {
      this.docV2 = docV2;
      return this;
    }

    @Override
    public DetailsResponse build() {
      return new DetailsResponse(this);
    }
  }
}
