// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Documents.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class EditorialSeriesContainer extends Message {

  public static final String DEFAULT_SERIESTITLE = "";
  public static final String DEFAULT_SERIESSUBTITLE = "";
  public static final String DEFAULT_EPISODETITLE = "";
  public static final String DEFAULT_EPISODESUBTITLE = "";
  public static final String DEFAULT_COLORTHEMEARGB = "";

  @ProtoField(tag = 1, type = STRING)
  public final String seriesTitle;

  @ProtoField(tag = 2, type = STRING)
  public final String seriesSubtitle;

  @ProtoField(tag = 3, type = STRING)
  public final String episodeTitle;

  @ProtoField(tag = 4, type = STRING)
  public final String episodeSubtitle;

  @ProtoField(tag = 5, type = STRING)
  public final String colorThemeArgb;

  public EditorialSeriesContainer(String seriesTitle, String seriesSubtitle, String episodeTitle, String episodeSubtitle, String colorThemeArgb) {
    this.seriesTitle = seriesTitle;
    this.seriesSubtitle = seriesSubtitle;
    this.episodeTitle = episodeTitle;
    this.episodeSubtitle = episodeSubtitle;
    this.colorThemeArgb = colorThemeArgb;
  }

  private EditorialSeriesContainer(Builder builder) {
    this(builder.seriesTitle, builder.seriesSubtitle, builder.episodeTitle, builder.episodeSubtitle, builder.colorThemeArgb);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof EditorialSeriesContainer)) return false;
    EditorialSeriesContainer o = (EditorialSeriesContainer) other;
    return equals(seriesTitle, o.seriesTitle)
        && equals(seriesSubtitle, o.seriesSubtitle)
        && equals(episodeTitle, o.episodeTitle)
        && equals(episodeSubtitle, o.episodeSubtitle)
        && equals(colorThemeArgb, o.colorThemeArgb);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = seriesTitle != null ? seriesTitle.hashCode() : 0;
      result = result * 37 + (seriesSubtitle != null ? seriesSubtitle.hashCode() : 0);
      result = result * 37 + (episodeTitle != null ? episodeTitle.hashCode() : 0);
      result = result * 37 + (episodeSubtitle != null ? episodeSubtitle.hashCode() : 0);
      result = result * 37 + (colorThemeArgb != null ? colorThemeArgb.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<EditorialSeriesContainer> {

    public String seriesTitle;
    public String seriesSubtitle;
    public String episodeTitle;
    public String episodeSubtitle;
    public String colorThemeArgb;

    public Builder() {
    }

    public Builder(EditorialSeriesContainer message) {
      super(message);
      if (message == null) return;
      this.seriesTitle = message.seriesTitle;
      this.seriesSubtitle = message.seriesSubtitle;
      this.episodeTitle = message.episodeTitle;
      this.episodeSubtitle = message.episodeSubtitle;
      this.colorThemeArgb = message.colorThemeArgb;
    }

    public Builder seriesTitle(String seriesTitle) {
      this.seriesTitle = seriesTitle;
      return this;
    }

    public Builder seriesSubtitle(String seriesSubtitle) {
      this.seriesSubtitle = seriesSubtitle;
      return this;
    }

    public Builder episodeTitle(String episodeTitle) {
      this.episodeTitle = episodeTitle;
      return this;
    }

    public Builder episodeSubtitle(String episodeSubtitle) {
      this.episodeSubtitle = episodeSubtitle;
      return this;
    }

    public Builder colorThemeArgb(String colorThemeArgb) {
      this.colorThemeArgb = colorThemeArgb;
      return this;
    }

    @Override
    public EditorialSeriesContainer build() {
      return new EditorialSeriesContainer(this);
    }
  }
}
