// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Offers.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

public final class FilterEvaluationInfo extends Message {

  public static final List<RuleEvaluation> DEFAULT_RULEEVALUATION = Collections.emptyList();

  @ProtoField(tag = 1, label = REPEATED)
  public final List<RuleEvaluation> ruleEvaluation;

  public FilterEvaluationInfo(List<RuleEvaluation> ruleEvaluation) {
    this.ruleEvaluation = immutableCopyOf(ruleEvaluation);
  }

  private FilterEvaluationInfo(Builder builder) {
    this(builder.ruleEvaluation);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof FilterEvaluationInfo)) return false;
    return equals(ruleEvaluation, ((FilterEvaluationInfo) other).ruleEvaluation);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = ruleEvaluation != null ? ruleEvaluation.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<FilterEvaluationInfo> {

    public List<RuleEvaluation> ruleEvaluation;

    public Builder() {
    }

    public Builder(FilterEvaluationInfo message) {
      super(message);
      if (message == null) return;
      this.ruleEvaluation = copyOf(message.ruleEvaluation);
    }

    public Builder ruleEvaluation(List<RuleEvaluation> ruleEvaluation) {
      this.ruleEvaluation = checkForNulls(ruleEvaluation);
      return this;
    }

    @Override
    public FilterEvaluationInfo build() {
      return new FilterEvaluationInfo(this);
    }
  }
}
