// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Unsorted.proto
package com.google.play.proto;

import com.squareup.wire.Message;

public final class FlagContentResponse extends Message {

  public FlagContentResponse() {
  }

  private FlagContentResponse(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof FlagContentResponse;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<FlagContentResponse> {

    public Builder() {
    }

    public Builder(FlagContentResponse message) {
      super(message);
    }

    @Override
    public FlagContentResponse build() {
      return new FlagContentResponse(this);
    }
  }
}
