// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Unsorted.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class InitiateAssociationResponse extends Message {

  public static final String DEFAULT_USERTOKEN = "";

  @ProtoField(tag = 1, type = STRING)
  public final String userToken;

  public InitiateAssociationResponse(String userToken) {
    this.userToken = userToken;
  }

  private InitiateAssociationResponse(Builder builder) {
    this(builder.userToken);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof InitiateAssociationResponse)) return false;
    return equals(userToken, ((InitiateAssociationResponse) other).userToken);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = userToken != null ? userToken.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<InitiateAssociationResponse> {

    public String userToken;

    public Builder() {
    }

    public Builder(InitiateAssociationResponse message) {
      super(message);
      if (message == null) return;
      this.userToken = message.userToken;
    }

    public Builder userToken(String userToken) {
      this.userToken = userToken;
      return this;
    }

    @Override
    public InitiateAssociationResponse build() {
      return new InitiateAssociationResponse(this);
    }
  }
}
