// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Library.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;

public final class LibraryAppDetails extends Message {

  public static final String DEFAULT_CERTIFICATEHASH = "";
  public static final Long DEFAULT_REFUNDTIMEOUTTIMESTAMPMSEC = 0L;
  public static final Long DEFAULT_POSTDELIVERYREFUNDWINDOWMSEC = 0L;

  @ProtoField(tag = 2, type = STRING)
  public final String certificateHash;

  @ProtoField(tag = 3, type = INT64)
  public final Long refundTimeoutTimestampMsec;

  @ProtoField(tag = 4, type = INT64)
  public final Long postDeliveryRefundWindowMsec;

  public LibraryAppDetails(String certificateHash, Long refundTimeoutTimestampMsec, Long postDeliveryRefundWindowMsec) {
    this.certificateHash = certificateHash;
    this.refundTimeoutTimestampMsec = refundTimeoutTimestampMsec;
    this.postDeliveryRefundWindowMsec = postDeliveryRefundWindowMsec;
  }

  private LibraryAppDetails(Builder builder) {
    this(builder.certificateHash, builder.refundTimeoutTimestampMsec, builder.postDeliveryRefundWindowMsec);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof LibraryAppDetails)) return false;
    LibraryAppDetails o = (LibraryAppDetails) other;
    return equals(certificateHash, o.certificateHash)
        && equals(refundTimeoutTimestampMsec, o.refundTimeoutTimestampMsec)
        && equals(postDeliveryRefundWindowMsec, o.postDeliveryRefundWindowMsec);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = certificateHash != null ? certificateHash.hashCode() : 0;
      result = result * 37 + (refundTimeoutTimestampMsec != null ? refundTimeoutTimestampMsec.hashCode() : 0);
      result = result * 37 + (postDeliveryRefundWindowMsec != null ? postDeliveryRefundWindowMsec.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<LibraryAppDetails> {

    public String certificateHash;
    public Long refundTimeoutTimestampMsec;
    public Long postDeliveryRefundWindowMsec;

    public Builder() {
    }

    public Builder(LibraryAppDetails message) {
      super(message);
      if (message == null) return;
      this.certificateHash = message.certificateHash;
      this.refundTimeoutTimestampMsec = message.refundTimeoutTimestampMsec;
      this.postDeliveryRefundWindowMsec = message.postDeliveryRefundWindowMsec;
    }

    public Builder certificateHash(String certificateHash) {
      this.certificateHash = certificateHash;
      return this;
    }

    public Builder refundTimeoutTimestampMsec(Long refundTimeoutTimestampMsec) {
      this.refundTimeoutTimestampMsec = refundTimeoutTimestampMsec;
      return this;
    }

    public Builder postDeliveryRefundWindowMsec(Long postDeliveryRefundWindowMsec) {
      this.postDeliveryRefundWindowMsec = postDeliveryRefundWindowMsec;
      return this;
    }

    @Override
    public LibraryAppDetails build() {
      return new LibraryAppDetails(this);
    }
  }
}
