// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Purchase.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class LineItem extends Message {

  public static final String DEFAULT_NAME = "";
  public static final String DEFAULT_DESCRIPTION = "";

  @ProtoField(tag = 1, type = STRING)
  public final String name;

  @ProtoField(tag = 2, type = STRING)
  public final String description;

  @ProtoField(tag = 3)
  public final Offer offer;

  @ProtoField(tag = 4)
  public final Money amount;

  public LineItem(String name, String description, Offer offer, Money amount) {
    this.name = name;
    this.description = description;
    this.offer = offer;
    this.amount = amount;
  }

  private LineItem(Builder builder) {
    this(builder.name, builder.description, builder.offer, builder.amount);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof LineItem)) return false;
    LineItem o = (LineItem) other;
    return equals(name, o.name)
        && equals(description, o.description)
        && equals(offer, o.offer)
        && equals(amount, o.amount);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = name != null ? name.hashCode() : 0;
      result = result * 37 + (description != null ? description.hashCode() : 0);
      result = result * 37 + (offer != null ? offer.hashCode() : 0);
      result = result * 37 + (amount != null ? amount.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<LineItem> {

    public String name;
    public String description;
    public Offer offer;
    public Money amount;

    public Builder() {
    }

    public Builder(LineItem message) {
      super(message);
      if (message == null) return;
      this.name = message.name;
      this.description = message.description;
      this.offer = message.offer;
      this.amount = message.amount;
    }

    public Builder name(String name) {
      this.name = name;
      return this;
    }

    public Builder description(String description) {
      this.description = description;
      return this;
    }

    public Builder offer(Offer offer) {
      this.offer = offer;
      return this;
    }

    public Builder amount(Money amount) {
      this.amount = amount;
      return this;
    }

    @Override
    public LineItem build() {
      return new LineItem(this);
    }
  }
}
