// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Offers.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.INT64;

public final class OwnershipInfo extends Message {

  public static final Long DEFAULT_INITIATIONTIMESTAMPMSEC = 0L;
  public static final Long DEFAULT_VALIDUNTILTIMESTAMPMSEC = 0L;
  public static final Boolean DEFAULT_AUTORENEWING = false;
  public static final Long DEFAULT_REFUNDTIMEOUTTIMESTAMPMSEC = 0L;
  public static final Long DEFAULT_POSTDELIVERYREFUNDWINDOWMSEC = 0L;

  @ProtoField(tag = 1, type = INT64)
  public final Long initiationTimestampMsec;

  @ProtoField(tag = 2, type = INT64)
  public final Long validUntilTimestampMsec;

  @ProtoField(tag = 3, type = BOOL)
  public final Boolean autoRenewing;

  @ProtoField(tag = 4, type = INT64)
  public final Long refundTimeoutTimestampMsec;

  @ProtoField(tag = 5, type = INT64)
  public final Long postDeliveryRefundWindowMsec;

  public OwnershipInfo(Long initiationTimestampMsec, Long validUntilTimestampMsec, Boolean autoRenewing, Long refundTimeoutTimestampMsec, Long postDeliveryRefundWindowMsec) {
    this.initiationTimestampMsec = initiationTimestampMsec;
    this.validUntilTimestampMsec = validUntilTimestampMsec;
    this.autoRenewing = autoRenewing;
    this.refundTimeoutTimestampMsec = refundTimeoutTimestampMsec;
    this.postDeliveryRefundWindowMsec = postDeliveryRefundWindowMsec;
  }

  private OwnershipInfo(Builder builder) {
    this(builder.initiationTimestampMsec, builder.validUntilTimestampMsec, builder.autoRenewing, builder.refundTimeoutTimestampMsec, builder.postDeliveryRefundWindowMsec);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof OwnershipInfo)) return false;
    OwnershipInfo o = (OwnershipInfo) other;
    return equals(initiationTimestampMsec, o.initiationTimestampMsec)
        && equals(validUntilTimestampMsec, o.validUntilTimestampMsec)
        && equals(autoRenewing, o.autoRenewing)
        && equals(refundTimeoutTimestampMsec, o.refundTimeoutTimestampMsec)
        && equals(postDeliveryRefundWindowMsec, o.postDeliveryRefundWindowMsec);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = initiationTimestampMsec != null ? initiationTimestampMsec.hashCode() : 0;
      result = result * 37 + (validUntilTimestampMsec != null ? validUntilTimestampMsec.hashCode() : 0);
      result = result * 37 + (autoRenewing != null ? autoRenewing.hashCode() : 0);
      result = result * 37 + (refundTimeoutTimestampMsec != null ? refundTimeoutTimestampMsec.hashCode() : 0);
      result = result * 37 + (postDeliveryRefundWindowMsec != null ? postDeliveryRefundWindowMsec.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<OwnershipInfo> {

    public Long initiationTimestampMsec;
    public Long validUntilTimestampMsec;
    public Boolean autoRenewing;
    public Long refundTimeoutTimestampMsec;
    public Long postDeliveryRefundWindowMsec;

    public Builder() {
    }

    public Builder(OwnershipInfo message) {
      super(message);
      if (message == null) return;
      this.initiationTimestampMsec = message.initiationTimestampMsec;
      this.validUntilTimestampMsec = message.validUntilTimestampMsec;
      this.autoRenewing = message.autoRenewing;
      this.refundTimeoutTimestampMsec = message.refundTimeoutTimestampMsec;
      this.postDeliveryRefundWindowMsec = message.postDeliveryRefundWindowMsec;
    }

    public Builder initiationTimestampMsec(Long initiationTimestampMsec) {
      this.initiationTimestampMsec = initiationTimestampMsec;
      return this;
    }

    public Builder validUntilTimestampMsec(Long validUntilTimestampMsec) {
      this.validUntilTimestampMsec = validUntilTimestampMsec;
      return this;
    }

    public Builder autoRenewing(Boolean autoRenewing) {
      this.autoRenewing = autoRenewing;
      return this;
    }

    public Builder refundTimeoutTimestampMsec(Long refundTimeoutTimestampMsec) {
      this.refundTimeoutTimestampMsec = refundTimeoutTimestampMsec;
      return this;
    }

    public Builder postDeliveryRefundWindowMsec(Long postDeliveryRefundWindowMsec) {
      this.postDeliveryRefundWindowMsec = postDeliveryRefundWindowMsec;
      return this;
    }

    @Override
    public OwnershipInfo build() {
      return new OwnershipInfo(this);
    }
  }
}
