// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Challenges.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class PasswordPrompt extends Message {

  public static final String DEFAULT_PROMPT = "";
  public static final String DEFAULT_FORGOTPASSWORDURL = "";

  @ProtoField(tag = 1, type = STRING)
  public final String prompt;

  @ProtoField(tag = 2, type = STRING)
  public final String forgotPasswordUrl;

  public PasswordPrompt(String prompt, String forgotPasswordUrl) {
    this.prompt = prompt;
    this.forgotPasswordUrl = forgotPasswordUrl;
  }

  private PasswordPrompt(Builder builder) {
    this(builder.prompt, builder.forgotPasswordUrl);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PasswordPrompt)) return false;
    PasswordPrompt o = (PasswordPrompt) other;
    return equals(prompt, o.prompt)
        && equals(forgotPasswordUrl, o.forgotPasswordUrl);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = prompt != null ? prompt.hashCode() : 0;
      result = result * 37 + (forgotPasswordUrl != null ? forgotPasswordUrl.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PasswordPrompt> {

    public String prompt;
    public String forgotPasswordUrl;

    public Builder() {
    }

    public Builder(PasswordPrompt message) {
      super(message);
      if (message == null) return;
      this.prompt = message.prompt;
      this.forgotPasswordUrl = message.forgotPasswordUrl;
    }

    public Builder prompt(String prompt) {
      this.prompt = prompt;
      return this;
    }

    public Builder forgotPasswordUrl(String forgotPasswordUrl) {
      this.forgotPasswordUrl = forgotPasswordUrl;
      return this;
    }

    @Override
    public PasswordPrompt build() {
      return new PasswordPrompt(this);
    }
  }
}
