// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Paypal.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class PaypalPreapprovalDetailsResponseProto extends Message {

  public static final String DEFAULT_PAYPALEMAIL = "";

  @ProtoField(tag = 1, type = STRING)
  public final String paypalEmail;

  @ProtoField(tag = 2)
  public final AddressProto address;

  public PaypalPreapprovalDetailsResponseProto(String paypalEmail, AddressProto address) {
    this.paypalEmail = paypalEmail;
    this.address = address;
  }

  private PaypalPreapprovalDetailsResponseProto(Builder builder) {
    this(builder.paypalEmail, builder.address);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PaypalPreapprovalDetailsResponseProto)) return false;
    PaypalPreapprovalDetailsResponseProto o = (PaypalPreapprovalDetailsResponseProto) other;
    return equals(paypalEmail, o.paypalEmail)
        && equals(address, o.address);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = paypalEmail != null ? paypalEmail.hashCode() : 0;
      result = result * 37 + (address != null ? address.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PaypalPreapprovalDetailsResponseProto> {

    public String paypalEmail;
    public AddressProto address;

    public Builder() {
    }

    public Builder(PaypalPreapprovalDetailsResponseProto message) {
      super(message);
      if (message == null) return;
      this.paypalEmail = message.paypalEmail;
      this.address = message.address;
    }

    public Builder paypalEmail(String paypalEmail) {
      this.paypalEmail = paypalEmail;
      return this;
    }

    public Builder address(AddressProto address) {
      this.address = address;
      return this;
    }

    @Override
    public PaypalPreapprovalDetailsResponseProto build() {
      return new PaypalPreapprovalDetailsResponseProto(this);
    }
  }
}
