// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Paypal.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.STRING;

public final class PaypalPreapprovalDetailsRequestProto extends Message {

  public static final Boolean DEFAULT_GETADDRESS = false;
  public static final String DEFAULT_PREAPPROVALKEY = "";

  @ProtoField(tag = 1, type = BOOL)
  public final Boolean getAddress;

  @ProtoField(tag = 2, type = STRING)
  public final String preapprovalKey;

  public PaypalPreapprovalDetailsRequestProto(Boolean getAddress, String preapprovalKey) {
    this.getAddress = getAddress;
    this.preapprovalKey = preapprovalKey;
  }

  private PaypalPreapprovalDetailsRequestProto(Builder builder) {
    this(builder.getAddress, builder.preapprovalKey);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PaypalPreapprovalDetailsRequestProto)) return false;
    PaypalPreapprovalDetailsRequestProto o = (PaypalPreapprovalDetailsRequestProto) other;
    return equals(getAddress, o.getAddress)
        && equals(preapprovalKey, o.preapprovalKey);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = getAddress != null ? getAddress.hashCode() : 0;
      result = result * 37 + (preapprovalKey != null ? preapprovalKey.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PaypalPreapprovalDetailsRequestProto> {

    public Boolean getAddress;
    public String preapprovalKey;

    public Builder() {
    }

    public Builder(PaypalPreapprovalDetailsRequestProto message) {
      super(message);
      if (message == null) return;
      this.getAddress = message.getAddress;
      this.preapprovalKey = message.preapprovalKey;
    }

    public Builder getAddress(Boolean getAddress) {
      this.getAddress = getAddress;
      return this;
    }

    public Builder preapprovalKey(String preapprovalKey) {
      this.preapprovalKey = preapprovalKey;
      return this;
    }

    @Override
    public PaypalPreapprovalDetailsRequestProto build() {
      return new PaypalPreapprovalDetailsRequestProto(this);
    }
  }
}
