// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/GooglePlus.proto
package com.google.play.proto;

import com.squareup.wire.Message;

public final class PlusOneResponse extends Message {

  public PlusOneResponse() {
  }

  private PlusOneResponse(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof PlusOneResponse;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<PlusOneResponse> {

    public Builder() {
    }

    public Builder(PlusOneResponse message) {
      super(message);
    }

    @Override
    public PlusOneResponse build() {
      return new PlusOneResponse(this);
    }
  }
}
