// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Purchase.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;

public final class PurchaseOrderResponseProto extends Message {

  public static final Integer DEFAULT_DEPRECATEDRESULTCODE = 0;

  @ProtoField(tag = 1, type = INT32)
  public final Integer deprecatedResultCode;

  @ProtoField(tag = 2)
  public final PurchaseInfoProto purchaseInfo;

  @ProtoField(tag = 3)
  public final ExternalAssetProto asset;

  @ProtoField(tag = 4)
  public final PurchaseResultProto purchaseResult;

  public PurchaseOrderResponseProto(Integer deprecatedResultCode, PurchaseInfoProto purchaseInfo, ExternalAssetProto asset, PurchaseResultProto purchaseResult) {
    this.deprecatedResultCode = deprecatedResultCode;
    this.purchaseInfo = purchaseInfo;
    this.asset = asset;
    this.purchaseResult = purchaseResult;
  }

  private PurchaseOrderResponseProto(Builder builder) {
    this(builder.deprecatedResultCode, builder.purchaseInfo, builder.asset, builder.purchaseResult);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PurchaseOrderResponseProto)) return false;
    PurchaseOrderResponseProto o = (PurchaseOrderResponseProto) other;
    return equals(deprecatedResultCode, o.deprecatedResultCode)
        && equals(purchaseInfo, o.purchaseInfo)
        && equals(asset, o.asset)
        && equals(purchaseResult, o.purchaseResult);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = deprecatedResultCode != null ? deprecatedResultCode.hashCode() : 0;
      result = result * 37 + (purchaseInfo != null ? purchaseInfo.hashCode() : 0);
      result = result * 37 + (asset != null ? asset.hashCode() : 0);
      result = result * 37 + (purchaseResult != null ? purchaseResult.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PurchaseOrderResponseProto> {

    public Integer deprecatedResultCode;
    public PurchaseInfoProto purchaseInfo;
    public ExternalAssetProto asset;
    public PurchaseResultProto purchaseResult;

    public Builder() {
    }

    public Builder(PurchaseOrderResponseProto message) {
      super(message);
      if (message == null) return;
      this.deprecatedResultCode = message.deprecatedResultCode;
      this.purchaseInfo = message.purchaseInfo;
      this.asset = message.asset;
      this.purchaseResult = message.purchaseResult;
    }

    public Builder deprecatedResultCode(Integer deprecatedResultCode) {
      this.deprecatedResultCode = deprecatedResultCode;
      return this;
    }

    public Builder purchaseInfo(PurchaseInfoProto purchaseInfo) {
      this.purchaseInfo = purchaseInfo;
      return this;
    }

    public Builder asset(ExternalAssetProto asset) {
      this.asset = asset;
      return this;
    }

    public Builder purchaseResult(PurchaseResultProto purchaseResult) {
      this.purchaseResult = purchaseResult;
      return this;
    }

    @Override
    public PurchaseOrderResponseProto build() {
      return new PurchaseOrderResponseProto(this);
    }
  }
}
