// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Purchase.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class PurchaseProductResponseProto extends Message {

  public static final String DEFAULT_TITLE = "";
  public static final String DEFAULT_ITEMTITLE = "";
  public static final String DEFAULT_ITEMDESCRIPTION = "";
  public static final String DEFAULT_MERCHANTFIELD = "";

  @ProtoField(tag = 1, type = STRING)
  public final String title;

  @ProtoField(tag = 2, type = STRING)
  public final String itemTitle;

  @ProtoField(tag = 3, type = STRING)
  public final String itemDescription;

  @ProtoField(tag = 4, type = STRING)
  public final String merchantField;

  public PurchaseProductResponseProto(String title, String itemTitle, String itemDescription, String merchantField) {
    this.title = title;
    this.itemTitle = itemTitle;
    this.itemDescription = itemDescription;
    this.merchantField = merchantField;
  }

  private PurchaseProductResponseProto(Builder builder) {
    this(builder.title, builder.itemTitle, builder.itemDescription, builder.merchantField);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PurchaseProductResponseProto)) return false;
    PurchaseProductResponseProto o = (PurchaseProductResponseProto) other;
    return equals(title, o.title)
        && equals(itemTitle, o.itemTitle)
        && equals(itemDescription, o.itemDescription)
        && equals(merchantField, o.merchantField);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = title != null ? title.hashCode() : 0;
      result = result * 37 + (itemTitle != null ? itemTitle.hashCode() : 0);
      result = result * 37 + (itemDescription != null ? itemDescription.hashCode() : 0);
      result = result * 37 + (merchantField != null ? merchantField.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PurchaseProductResponseProto> {

    public String title;
    public String itemTitle;
    public String itemDescription;
    public String merchantField;

    public Builder() {
    }

    public Builder(PurchaseProductResponseProto message) {
      super(message);
      if (message == null) return;
      this.title = message.title;
      this.itemTitle = message.itemTitle;
      this.itemDescription = message.itemDescription;
      this.merchantField = message.merchantField;
    }

    public Builder title(String title) {
      this.title = title;
      return this;
    }

    public Builder itemTitle(String itemTitle) {
      this.itemTitle = itemTitle;
      return this;
    }

    public Builder itemDescription(String itemDescription) {
      this.itemDescription = itemDescription;
      return this;
    }

    public Builder merchantField(String merchantField) {
      this.merchantField = merchantField;
      return this;
    }

    @Override
    public PurchaseProductResponseProto build() {
      return new PurchaseProductResponseProto(this);
    }
  }
}
