// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Purchase.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.STRING;

public final class PurchaseNotificationResponse extends Message {

  public static final Integer DEFAULT_STATUS = 0;
  public static final String DEFAULT_LOCALIZEDERRORMESSAGE = "";
  public static final String DEFAULT_PURCHASEID = "";

  @ProtoField(tag = 1, type = INT32)
  public final Integer status;

  @ProtoField(tag = 2)
  public final DebugInfo debugInfo;

  @ProtoField(tag = 3, type = STRING)
  public final String localizedErrorMessage;

  @ProtoField(tag = 4, type = STRING)
  public final String purchaseId;

  public PurchaseNotificationResponse(Integer status, DebugInfo debugInfo, String localizedErrorMessage, String purchaseId) {
    this.status = status;
    this.debugInfo = debugInfo;
    this.localizedErrorMessage = localizedErrorMessage;
    this.purchaseId = purchaseId;
  }

  private PurchaseNotificationResponse(Builder builder) {
    this(builder.status, builder.debugInfo, builder.localizedErrorMessage, builder.purchaseId);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PurchaseNotificationResponse)) return false;
    PurchaseNotificationResponse o = (PurchaseNotificationResponse) other;
    return equals(status, o.status)
        && equals(debugInfo, o.debugInfo)
        && equals(localizedErrorMessage, o.localizedErrorMessage)
        && equals(purchaseId, o.purchaseId);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = status != null ? status.hashCode() : 0;
      result = result * 37 + (debugInfo != null ? debugInfo.hashCode() : 0);
      result = result * 37 + (localizedErrorMessage != null ? localizedErrorMessage.hashCode() : 0);
      result = result * 37 + (purchaseId != null ? purchaseId.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PurchaseNotificationResponse> {

    public Integer status;
    public DebugInfo debugInfo;
    public String localizedErrorMessage;
    public String purchaseId;

    public Builder() {
    }

    public Builder(PurchaseNotificationResponse message) {
      super(message);
      if (message == null) return;
      this.status = message.status;
      this.debugInfo = message.debugInfo;
      this.localizedErrorMessage = message.localizedErrorMessage;
      this.purchaseId = message.purchaseId;
    }

    public Builder status(Integer status) {
      this.status = status;
      return this;
    }

    public Builder debugInfo(DebugInfo debugInfo) {
      this.debugInfo = debugInfo;
      return this;
    }

    public Builder localizedErrorMessage(String localizedErrorMessage) {
      this.localizedErrorMessage = localizedErrorMessage;
      return this;
    }

    public Builder purchaseId(String purchaseId) {
      this.purchaseId = purchaseId;
      return this;
    }

    @Override
    public PurchaseNotificationResponse build() {
      return new PurchaseNotificationResponse(this);
    }
  }
}
