// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Browse.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.STRING;

public final class QuickLink extends Message {

  public static final String DEFAULT_NAME = "";
  public static final Boolean DEFAULT_DISPLAYREQUIRED = false;
  public static final ByteString DEFAULT_SERVERLOGSCOOKIE = ByteString.EMPTY;

  @ProtoField(tag = 1, type = STRING)
  public final String name;

  @ProtoField(tag = 2)
  public final Image image;

  @ProtoField(tag = 3)
  public final ResolvedLink link;

  @ProtoField(tag = 4, type = BOOL)
  public final Boolean displayRequired;

  @ProtoField(tag = 5, type = BYTES)
  public final ByteString serverLogsCookie;

  public QuickLink(String name, Image image, ResolvedLink link, Boolean displayRequired, ByteString serverLogsCookie) {
    this.name = name;
    this.image = image;
    this.link = link;
    this.displayRequired = displayRequired;
    this.serverLogsCookie = serverLogsCookie;
  }

  private QuickLink(Builder builder) {
    this(builder.name, builder.image, builder.link, builder.displayRequired, builder.serverLogsCookie);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof QuickLink)) return false;
    QuickLink o = (QuickLink) other;
    return equals(name, o.name)
        && equals(image, o.image)
        && equals(link, o.link)
        && equals(displayRequired, o.displayRequired)
        && equals(serverLogsCookie, o.serverLogsCookie);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = name != null ? name.hashCode() : 0;
      result = result * 37 + (image != null ? image.hashCode() : 0);
      result = result * 37 + (link != null ? link.hashCode() : 0);
      result = result * 37 + (displayRequired != null ? displayRequired.hashCode() : 0);
      result = result * 37 + (serverLogsCookie != null ? serverLogsCookie.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<QuickLink> {

    public String name;
    public Image image;
    public ResolvedLink link;
    public Boolean displayRequired;
    public ByteString serverLogsCookie;

    public Builder() {
    }

    public Builder(QuickLink message) {
      super(message);
      if (message == null) return;
      this.name = message.name;
      this.image = message.image;
      this.link = message.link;
      this.displayRequired = message.displayRequired;
      this.serverLogsCookie = message.serverLogsCookie;
    }

    public Builder name(String name) {
      this.name = name;
      return this;
    }

    public Builder image(Image image) {
      this.image = image;
      return this;
    }

    public Builder link(ResolvedLink link) {
      this.link = link;
      return this;
    }

    public Builder displayRequired(Boolean displayRequired) {
      this.displayRequired = displayRequired;
      return this;
    }

    public Builder serverLogsCookie(ByteString serverLogsCookie) {
      this.serverLogsCookie = serverLogsCookie;
      return this;
    }

    @Override
    public QuickLink build() {
      return new QuickLink(this);
    }
  }
}
