// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Purchase.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.STRING;

public final class RefundResponseProto extends Message {

  public static final Integer DEFAULT_RESULT = 0;
  public static final String DEFAULT_RESULTDETAIL = "";

  @ProtoField(tag = 1, type = INT32)
  public final Integer result;

  @ProtoField(tag = 2)
  public final ExternalAssetProto asset;

  @ProtoField(tag = 3, type = STRING)
  public final String resultDetail;

  public RefundResponseProto(Integer result, ExternalAssetProto asset, String resultDetail) {
    this.result = result;
    this.asset = asset;
    this.resultDetail = resultDetail;
  }

  private RefundResponseProto(Builder builder) {
    this(builder.result, builder.asset, builder.resultDetail);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RefundResponseProto)) return false;
    RefundResponseProto o = (RefundResponseProto) other;
    return equals(result, o.result)
        && equals(asset, o.asset)
        && equals(resultDetail, o.resultDetail);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = this.result != null ? this.result.hashCode() : 0;
      result = result * 37 + (asset != null ? asset.hashCode() : 0);
      result = result * 37 + (resultDetail != null ? resultDetail.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<RefundResponseProto> {

    public Integer result;
    public ExternalAssetProto asset;
    public String resultDetail;

    public Builder() {
    }

    public Builder(RefundResponseProto message) {
      super(message);
      if (message == null) return;
      this.result = message.result;
      this.asset = message.asset;
      this.resultDetail = message.resultDetail;
    }

    public Builder result(Integer result) {
      this.result = result;
      return this;
    }

    public Builder asset(ExternalAssetProto asset) {
      this.asset = asset;
      return this;
    }

    public Builder resultDetail(String resultDetail) {
      this.resultDetail = resultDetail;
      return this;
    }

    @Override
    public RefundResponseProto build() {
      return new RefundResponseProto(this);
    }
  }
}
