// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Requests.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.STRING;

public final class RequestPropertiesProto extends Message {

  public static final String DEFAULT_USERAUTHTOKEN = "";
  public static final Boolean DEFAULT_USERAUTHTOKENSECURE = false;
  public static final Integer DEFAULT_SOFTWAREVERSION = 0;
  public static final String DEFAULT_AID = "";
  public static final String DEFAULT_PRODUCTNAMEANDVERSION = "";
  public static final String DEFAULT_USERLANGUAGE = "";
  public static final String DEFAULT_USERCOUNTRY = "";
  public static final String DEFAULT_OPERATORNAME = "";
  public static final String DEFAULT_SIMOPERATORNAME = "";
  public static final String DEFAULT_OPERATORNUMERICNAME = "";
  public static final String DEFAULT_SIMOPERATORNUMERICNAME = "";
  public static final String DEFAULT_CLIENTID = "";
  public static final String DEFAULT_LOGGINGID = "";

  @ProtoField(tag = 1, type = STRING)
  public final String userAuthToken;

  @ProtoField(tag = 2, type = BOOL)
  public final Boolean userAuthTokenSecure;

  @ProtoField(tag = 3, type = INT32)
  public final Integer softwareVersion;

  @ProtoField(tag = 4, type = STRING)
  public final String aid;

  @ProtoField(tag = 5, type = STRING)
  public final String productNameAndVersion;

  @ProtoField(tag = 6, type = STRING)
  public final String userLanguage;

  @ProtoField(tag = 7, type = STRING)
  public final String userCountry;

  @ProtoField(tag = 8, type = STRING)
  public final String operatorName;

  @ProtoField(tag = 9, type = STRING)
  public final String simOperatorName;

  @ProtoField(tag = 10, type = STRING)
  public final String operatorNumericName;

  @ProtoField(tag = 11, type = STRING)
  public final String simOperatorNumericName;

  @ProtoField(tag = 12, type = STRING)
  public final String clientId;

  @ProtoField(tag = 13, type = STRING)
  public final String loggingId;

  public RequestPropertiesProto(String userAuthToken, Boolean userAuthTokenSecure, Integer softwareVersion, String aid, String productNameAndVersion, String userLanguage, String userCountry, String operatorName, String simOperatorName, String operatorNumericName, String simOperatorNumericName, String clientId, String loggingId) {
    this.userAuthToken = userAuthToken;
    this.userAuthTokenSecure = userAuthTokenSecure;
    this.softwareVersion = softwareVersion;
    this.aid = aid;
    this.productNameAndVersion = productNameAndVersion;
    this.userLanguage = userLanguage;
    this.userCountry = userCountry;
    this.operatorName = operatorName;
    this.simOperatorName = simOperatorName;
    this.operatorNumericName = operatorNumericName;
    this.simOperatorNumericName = simOperatorNumericName;
    this.clientId = clientId;
    this.loggingId = loggingId;
  }

  private RequestPropertiesProto(Builder builder) {
    this(builder.userAuthToken, builder.userAuthTokenSecure, builder.softwareVersion, builder.aid, builder.productNameAndVersion, builder.userLanguage, builder.userCountry, builder.operatorName, builder.simOperatorName, builder.operatorNumericName, builder.simOperatorNumericName, builder.clientId, builder.loggingId);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RequestPropertiesProto)) return false;
    RequestPropertiesProto o = (RequestPropertiesProto) other;
    return equals(userAuthToken, o.userAuthToken)
        && equals(userAuthTokenSecure, o.userAuthTokenSecure)
        && equals(softwareVersion, o.softwareVersion)
        && equals(aid, o.aid)
        && equals(productNameAndVersion, o.productNameAndVersion)
        && equals(userLanguage, o.userLanguage)
        && equals(userCountry, o.userCountry)
        && equals(operatorName, o.operatorName)
        && equals(simOperatorName, o.simOperatorName)
        && equals(operatorNumericName, o.operatorNumericName)
        && equals(simOperatorNumericName, o.simOperatorNumericName)
        && equals(clientId, o.clientId)
        && equals(loggingId, o.loggingId);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = userAuthToken != null ? userAuthToken.hashCode() : 0;
      result = result * 37 + (userAuthTokenSecure != null ? userAuthTokenSecure.hashCode() : 0);
      result = result * 37 + (softwareVersion != null ? softwareVersion.hashCode() : 0);
      result = result * 37 + (aid != null ? aid.hashCode() : 0);
      result = result * 37 + (productNameAndVersion != null ? productNameAndVersion.hashCode() : 0);
      result = result * 37 + (userLanguage != null ? userLanguage.hashCode() : 0);
      result = result * 37 + (userCountry != null ? userCountry.hashCode() : 0);
      result = result * 37 + (operatorName != null ? operatorName.hashCode() : 0);
      result = result * 37 + (simOperatorName != null ? simOperatorName.hashCode() : 0);
      result = result * 37 + (operatorNumericName != null ? operatorNumericName.hashCode() : 0);
      result = result * 37 + (simOperatorNumericName != null ? simOperatorNumericName.hashCode() : 0);
      result = result * 37 + (clientId != null ? clientId.hashCode() : 0);
      result = result * 37 + (loggingId != null ? loggingId.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<RequestPropertiesProto> {

    public String userAuthToken;
    public Boolean userAuthTokenSecure;
    public Integer softwareVersion;
    public String aid;
    public String productNameAndVersion;
    public String userLanguage;
    public String userCountry;
    public String operatorName;
    public String simOperatorName;
    public String operatorNumericName;
    public String simOperatorNumericName;
    public String clientId;
    public String loggingId;

    public Builder() {
    }

    public Builder(RequestPropertiesProto message) {
      super(message);
      if (message == null) return;
      this.userAuthToken = message.userAuthToken;
      this.userAuthTokenSecure = message.userAuthTokenSecure;
      this.softwareVersion = message.softwareVersion;
      this.aid = message.aid;
      this.productNameAndVersion = message.productNameAndVersion;
      this.userLanguage = message.userLanguage;
      this.userCountry = message.userCountry;
      this.operatorName = message.operatorName;
      this.simOperatorName = message.simOperatorName;
      this.operatorNumericName = message.operatorNumericName;
      this.simOperatorNumericName = message.simOperatorNumericName;
      this.clientId = message.clientId;
      this.loggingId = message.loggingId;
    }

    public Builder userAuthToken(String userAuthToken) {
      this.userAuthToken = userAuthToken;
      return this;
    }

    public Builder userAuthTokenSecure(Boolean userAuthTokenSecure) {
      this.userAuthTokenSecure = userAuthTokenSecure;
      return this;
    }

    public Builder softwareVersion(Integer softwareVersion) {
      this.softwareVersion = softwareVersion;
      return this;
    }

    public Builder aid(String aid) {
      this.aid = aid;
      return this;
    }

    public Builder productNameAndVersion(String productNameAndVersion) {
      this.productNameAndVersion = productNameAndVersion;
      return this;
    }

    public Builder userLanguage(String userLanguage) {
      this.userLanguage = userLanguage;
      return this;
    }

    public Builder userCountry(String userCountry) {
      this.userCountry = userCountry;
      return this;
    }

    public Builder operatorName(String operatorName) {
      this.operatorName = operatorName;
      return this;
    }

    public Builder simOperatorName(String simOperatorName) {
      this.simOperatorName = simOperatorName;
      return this;
    }

    public Builder operatorNumericName(String operatorNumericName) {
      this.operatorNumericName = operatorNumericName;
      return this;
    }

    public Builder simOperatorNumericName(String simOperatorNumericName) {
      this.simOperatorNumericName = simOperatorNumericName;
      return this;
    }

    public Builder clientId(String clientId) {
      this.clientId = clientId;
      return this;
    }

    public Builder loggingId(String loggingId) {
      this.loggingId = loggingId;
      return this;
    }

    @Override
    public RequestPropertiesProto build() {
      return new RequestPropertiesProto(this);
    }
  }
}
