// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Unsorted.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class ResolveLinkResponse extends Message {

  public static final String DEFAULT_DETAILSURL = "";
  public static final String DEFAULT_BROWSEURL = "";
  public static final String DEFAULT_SEARCHURL = "";
  public static final String DEFAULT_HOMEURL = "";

  @ProtoField(tag = 1, type = STRING)
  public final String detailsUrl;

  @ProtoField(tag = 2, type = STRING)
  public final String browseUrl;

  @ProtoField(tag = 3, type = STRING)
  public final String searchUrl;

  @ProtoField(tag = 4)
  public final DirectPurchase directPurchase;

  @ProtoField(tag = 5, type = STRING)
  public final String homeUrl;

  public ResolveLinkResponse(String detailsUrl, String browseUrl, String searchUrl, DirectPurchase directPurchase, String homeUrl) {
    this.detailsUrl = detailsUrl;
    this.browseUrl = browseUrl;
    this.searchUrl = searchUrl;
    this.directPurchase = directPurchase;
    this.homeUrl = homeUrl;
  }

  private ResolveLinkResponse(Builder builder) {
    this(builder.detailsUrl, builder.browseUrl, builder.searchUrl, builder.directPurchase, builder.homeUrl);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ResolveLinkResponse)) return false;
    ResolveLinkResponse o = (ResolveLinkResponse) other;
    return equals(detailsUrl, o.detailsUrl)
        && equals(browseUrl, o.browseUrl)
        && equals(searchUrl, o.searchUrl)
        && equals(directPurchase, o.directPurchase)
        && equals(homeUrl, o.homeUrl);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = detailsUrl != null ? detailsUrl.hashCode() : 0;
      result = result * 37 + (browseUrl != null ? browseUrl.hashCode() : 0);
      result = result * 37 + (searchUrl != null ? searchUrl.hashCode() : 0);
      result = result * 37 + (directPurchase != null ? directPurchase.hashCode() : 0);
      result = result * 37 + (homeUrl != null ? homeUrl.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ResolveLinkResponse> {

    public String detailsUrl;
    public String browseUrl;
    public String searchUrl;
    public DirectPurchase directPurchase;
    public String homeUrl;

    public Builder() {
    }

    public Builder(ResolveLinkResponse message) {
      super(message);
      if (message == null) return;
      this.detailsUrl = message.detailsUrl;
      this.browseUrl = message.browseUrl;
      this.searchUrl = message.searchUrl;
      this.directPurchase = message.directPurchase;
      this.homeUrl = message.homeUrl;
    }

    public Builder detailsUrl(String detailsUrl) {
      this.detailsUrl = detailsUrl;
      return this;
    }

    public Builder browseUrl(String browseUrl) {
      this.browseUrl = browseUrl;
      return this;
    }

    public Builder searchUrl(String searchUrl) {
      this.searchUrl = searchUrl;
      return this;
    }

    public Builder directPurchase(DirectPurchase directPurchase) {
      this.directPurchase = directPurchase;
      return this;
    }

    public Builder homeUrl(String homeUrl) {
      this.homeUrl = homeUrl;
      return this;
    }

    @Override
    public ResolveLinkResponse build() {
      return new ResolveLinkResponse(this);
    }
  }
}
