// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Unsorted.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

public final class RestoreApplicationsResponseProto extends Message {

  public static final List<GetAssetResponseProto> DEFAULT_ASSET = Collections.emptyList();

  @ProtoField(tag = 1, label = REPEATED)
  public final List<GetAssetResponseProto> asset;

  public RestoreApplicationsResponseProto(List<GetAssetResponseProto> asset) {
    this.asset = immutableCopyOf(asset);
  }

  private RestoreApplicationsResponseProto(Builder builder) {
    this(builder.asset);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RestoreApplicationsResponseProto)) return false;
    return equals(asset, ((RestoreApplicationsResponseProto) other).asset);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = asset != null ? asset.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<RestoreApplicationsResponseProto> {

    public List<GetAssetResponseProto> asset;

    public Builder() {
    }

    public Builder(RestoreApplicationsResponseProto message) {
      super(message);
      if (message == null) return;
      this.asset = copyOf(message.asset);
    }

    public Builder asset(List<GetAssetResponseProto> asset) {
      this.asset = checkForNulls(asset);
      return this;
    }

    @Override
    public RestoreApplicationsResponseProto build() {
      return new RestoreApplicationsResponseProto(this);
    }
  }
}
