// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Unsorted.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class StatusBarNotificationProto extends Message {

  public static final String DEFAULT_TICKERTEXT = "";
  public static final String DEFAULT_CONTENTTITLE = "";
  public static final String DEFAULT_CONTENTTEXT = "";

  @ProtoField(tag = 1, type = STRING)
  public final String tickerText;

  @ProtoField(tag = 2, type = STRING)
  public final String contentTitle;

  @ProtoField(tag = 3, type = STRING)
  public final String contentText;

  public StatusBarNotificationProto(String tickerText, String contentTitle, String contentText) {
    this.tickerText = tickerText;
    this.contentTitle = contentTitle;
    this.contentText = contentText;
  }

  private StatusBarNotificationProto(Builder builder) {
    this(builder.tickerText, builder.contentTitle, builder.contentText);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof StatusBarNotificationProto)) return false;
    StatusBarNotificationProto o = (StatusBarNotificationProto) other;
    return equals(tickerText, o.tickerText)
        && equals(contentTitle, o.contentTitle)
        && equals(contentText, o.contentText);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = tickerText != null ? tickerText.hashCode() : 0;
      result = result * 37 + (contentTitle != null ? contentTitle.hashCode() : 0);
      result = result * 37 + (contentText != null ? contentText.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<StatusBarNotificationProto> {

    public String tickerText;
    public String contentTitle;
    public String contentText;

    public Builder() {
    }

    public Builder(StatusBarNotificationProto message) {
      super(message);
      if (message == null) return;
      this.tickerText = message.tickerText;
      this.contentTitle = message.contentTitle;
      this.contentText = message.contentText;
    }

    public Builder tickerText(String tickerText) {
      this.tickerText = tickerText;
      return this;
    }

    public Builder contentTitle(String contentTitle) {
      this.contentTitle = contentTitle;
      return this;
    }

    public Builder contentText(String contentText) {
      this.contentText = contentText;
      return this;
    }

    @Override
    public StatusBarNotificationProto build() {
      return new StatusBarNotificationProto(this);
    }
  }
}
