// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Offers.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;

public final class TimePeriod extends Message {

  public static final Integer DEFAULT_UNIT = 0;
  public static final Integer DEFAULT_COUNT = 0;

  @ProtoField(tag = 1, type = INT32)
  public final Integer unit;

  @ProtoField(tag = 2, type = INT32)
  public final Integer count;

  public TimePeriod(Integer unit, Integer count) {
    this.unit = unit;
    this.count = count;
  }

  private TimePeriod(Builder builder) {
    this(builder.unit, builder.count);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof TimePeriod)) return false;
    TimePeriod o = (TimePeriod) other;
    return equals(unit, o.unit)
        && equals(count, o.count);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = unit != null ? unit.hashCode() : 0;
      result = result * 37 + (count != null ? count.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<TimePeriod> {

    public Integer unit;
    public Integer count;

    public Builder() {
    }

    public Builder(TimePeriod message) {
      super(message);
      if (message == null) return;
      this.unit = message.unit;
      this.count = message.count;
    }

    public Builder unit(Integer unit) {
      this.unit = unit;
      return this;
    }

    public Builder count(Integer count) {
      this.count = count;
      return this;
    }

    @Override
    public TimePeriod build() {
      return new TimePeriod(this);
    }
  }
}
