// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/UploadDeviceConfig.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class UploadDeviceConfigRequest extends Message {

  public static final String DEFAULT_MANUFACTURER = "";
  public static final String DEFAULT_GCMREGISTRATIONID = "";

  @ProtoField(tag = 1)
  public final DeviceConfig deviceConfiguration;

  @ProtoField(tag = 2, type = STRING)
  public final String manufacturer;

  @ProtoField(tag = 3, type = STRING)
  public final String gcmRegistrationId;

  public UploadDeviceConfigRequest(DeviceConfig deviceConfiguration, String manufacturer, String gcmRegistrationId) {
    this.deviceConfiguration = deviceConfiguration;
    this.manufacturer = manufacturer;
    this.gcmRegistrationId = gcmRegistrationId;
  }

  private UploadDeviceConfigRequest(Builder builder) {
    this(builder.deviceConfiguration, builder.manufacturer, builder.gcmRegistrationId);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof UploadDeviceConfigRequest)) return false;
    UploadDeviceConfigRequest o = (UploadDeviceConfigRequest) other;
    return equals(deviceConfiguration, o.deviceConfiguration)
        && equals(manufacturer, o.manufacturer)
        && equals(gcmRegistrationId, o.gcmRegistrationId);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = deviceConfiguration != null ? deviceConfiguration.hashCode() : 0;
      result = result * 37 + (manufacturer != null ? manufacturer.hashCode() : 0);
      result = result * 37 + (gcmRegistrationId != null ? gcmRegistrationId.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<UploadDeviceConfigRequest> {

    public DeviceConfig deviceConfiguration;
    public String manufacturer;
    public String gcmRegistrationId;

    public Builder() {
    }

    public Builder(UploadDeviceConfigRequest message) {
      super(message);
      if (message == null) return;
      this.deviceConfiguration = message.deviceConfiguration;
      this.manufacturer = message.manufacturer;
      this.gcmRegistrationId = message.gcmRegistrationId;
    }

    public Builder deviceConfiguration(DeviceConfig deviceConfiguration) {
      this.deviceConfiguration = deviceConfiguration;
      return this;
    }

    public Builder manufacturer(String manufacturer) {
      this.manufacturer = manufacturer;
      return this;
    }

    public Builder gcmRegistrationId(String gcmRegistrationId) {
      this.gcmRegistrationId = gcmRegistrationId;
      return this;
    }

    @Override
    public UploadDeviceConfigRequest build() {
      return new UploadDeviceConfigRequest(this);
    }
  }
}
