// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Notifications.proto
package com.google.play.proto;

import com.squareup.wire.Message;

public final class AckNotificationsResponseProto extends Message {

  public AckNotificationsResponseProto() {
  }

  private AckNotificationsResponseProto(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof AckNotificationsResponseProto;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<AckNotificationsResponseProto> {

    public Builder() {
    }

    public Builder(AckNotificationsResponseProto message) {
      super(message);
    }

    @Override
    public AckNotificationsResponseProto build() {
      return new AckNotificationsResponseProto(this);
    }
  }
}
