/*
 * Copyright (c) 2014 μg Project Team
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Purchase.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REPEATED;

public final class BillingInstrumentsProto extends Message {

  public static final List<BillingInstrumentProto> DEFAULT_BILLINGINSTRUMENT = Collections.emptyList();
  public static final String DEFAULT_DEFAULTBILLINGINSTRUMENTID = "";

  @ProtoField(tag = 4, label = REPEATED)
  public final List<BillingInstrumentProto> billingInstrument;

  @ProtoField(tag = 8, type = STRING)
  public final String defaultBillingInstrumentId;

  public BillingInstrumentsProto(List<BillingInstrumentProto> billingInstrument, String defaultBillingInstrumentId) {
    this.billingInstrument = immutableCopyOf(billingInstrument);
    this.defaultBillingInstrumentId = defaultBillingInstrumentId;
  }

  private BillingInstrumentsProto(Builder builder) {
    this(builder.billingInstrument, builder.defaultBillingInstrumentId);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof BillingInstrumentsProto)) return false;
    BillingInstrumentsProto o = (BillingInstrumentsProto) other;
    return equals(billingInstrument, o.billingInstrument)
        && equals(defaultBillingInstrumentId, o.defaultBillingInstrumentId);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = billingInstrument != null ? billingInstrument.hashCode() : 1;
      result = result * 37 + (defaultBillingInstrumentId != null ? defaultBillingInstrumentId.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<BillingInstrumentsProto> {

    public List<BillingInstrumentProto> billingInstrument;
    public String defaultBillingInstrumentId;

    public Builder() {
    }

    public Builder(BillingInstrumentsProto message) {
      super(message);
      if (message == null) return;
      this.billingInstrument = copyOf(message.billingInstrument);
      this.defaultBillingInstrumentId = message.defaultBillingInstrumentId;
    }

    public Builder billingInstrument(List<BillingInstrumentProto> billingInstrument) {
      this.billingInstrument = checkForNulls(billingInstrument);
      return this;
    }

    public Builder defaultBillingInstrumentId(String defaultBillingInstrumentId) {
      this.defaultBillingInstrumentId = defaultBillingInstrumentId;
      return this;
    }

    @Override
    public BillingInstrumentsProto build() {
      return new BillingInstrumentsProto(this);
    }
  }
}
