/*
 * Copyright (c) 2014 μg Project Team
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Documents.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.*;

public final class ContainerMetadata extends Message {

  public static final String DEFAULT_BROWSEURL = "";
  public static final String DEFAULT_NEXTPAGEURL = "";
  public static final Double DEFAULT_RELEVANCE = 0D;
  public static final Long DEFAULT_ESTIMATEDRESULTS = 0L;
  public static final String DEFAULT_ANALYTICSCOOKIE = "";
  public static final Boolean DEFAULT_ORDERED = false;

  @ProtoField(tag = 1, type = STRING)
  public final String browseUrl;

  @ProtoField(tag = 2, type = STRING)
  public final String nextPageUrl;

  @ProtoField(tag = 3, type = DOUBLE)
  public final Double relevance;

  @ProtoField(tag = 4, type = INT64)
  public final Long estimatedResults;

  @ProtoField(tag = 5, type = STRING)
  public final String analyticsCookie;

  @ProtoField(tag = 6, type = BOOL)
  public final Boolean ordered;

  public ContainerMetadata(String browseUrl, String nextPageUrl, Double relevance, Long estimatedResults, String analyticsCookie, Boolean ordered) {
    this.browseUrl = browseUrl;
    this.nextPageUrl = nextPageUrl;
    this.relevance = relevance;
    this.estimatedResults = estimatedResults;
    this.analyticsCookie = analyticsCookie;
    this.ordered = ordered;
  }

  private ContainerMetadata(Builder builder) {
    this(builder.browseUrl, builder.nextPageUrl, builder.relevance, builder.estimatedResults, builder.analyticsCookie, builder.ordered);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ContainerMetadata)) return false;
    ContainerMetadata o = (ContainerMetadata) other;
    return equals(browseUrl, o.browseUrl)
        && equals(nextPageUrl, o.nextPageUrl)
        && equals(relevance, o.relevance)
        && equals(estimatedResults, o.estimatedResults)
        && equals(analyticsCookie, o.analyticsCookie)
        && equals(ordered, o.ordered);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = browseUrl != null ? browseUrl.hashCode() : 0;
      result = result * 37 + (nextPageUrl != null ? nextPageUrl.hashCode() : 0);
      result = result * 37 + (relevance != null ? relevance.hashCode() : 0);
      result = result * 37 + (estimatedResults != null ? estimatedResults.hashCode() : 0);
      result = result * 37 + (analyticsCookie != null ? analyticsCookie.hashCode() : 0);
      result = result * 37 + (ordered != null ? ordered.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ContainerMetadata> {

    public String browseUrl;
    public String nextPageUrl;
    public Double relevance;
    public Long estimatedResults;
    public String analyticsCookie;
    public Boolean ordered;

    public Builder() {
    }

    public Builder(ContainerMetadata message) {
      super(message);
      if (message == null) return;
      this.browseUrl = message.browseUrl;
      this.nextPageUrl = message.nextPageUrl;
      this.relevance = message.relevance;
      this.estimatedResults = message.estimatedResults;
      this.analyticsCookie = message.analyticsCookie;
      this.ordered = message.ordered;
    }

    public Builder browseUrl(String browseUrl) {
      this.browseUrl = browseUrl;
      return this;
    }

    public Builder nextPageUrl(String nextPageUrl) {
      this.nextPageUrl = nextPageUrl;
      return this;
    }

    public Builder relevance(Double relevance) {
      this.relevance = relevance;
      return this;
    }

    public Builder estimatedResults(Long estimatedResults) {
      this.estimatedResults = estimatedResults;
      return this;
    }

    public Builder analyticsCookie(String analyticsCookie) {
      this.analyticsCookie = analyticsCookie;
      return this;
    }

    public Builder ordered(Boolean ordered) {
      this.ordered = ordered;
      return this;
    }

    @Override
    public ContainerMetadata build() {
      return new ContainerMetadata(this);
    }
  }
}
