/*
 * Copyright (c) 2014 μg Project Team
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Purchase.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

public final class CountriesProto extends Message {

  public static final List<CountryProto> DEFAULT_COUNTRY = Collections.emptyList();

  @ProtoField(tag = 2, label = REPEATED)
  public final List<CountryProto> country;

  public CountriesProto(List<CountryProto> country) {
    this.country = immutableCopyOf(country);
  }

  private CountriesProto(Builder builder) {
    this(builder.country);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof CountriesProto)) return false;
    return equals(country, ((CountriesProto) other).country);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = country != null ? country.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<CountriesProto> {

    public List<CountryProto> country;

    public Builder() {
    }

    public Builder(CountriesProto message) {
      super(message);
      if (message == null) return;
      this.country = copyOf(message.country);
    }

    public Builder country(List<CountryProto> country) {
      this.country = checkForNulls(country);
      return this;
    }

    @Override
    public CountriesProto build() {
      return new CountriesProto(this);
    }
  }
}
