// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/BadgeImage.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;

public final class DimensionProto extends Message {

  public static final Integer DEFAULT_WIDTH = 0;
  public static final Integer DEFAULT_HEIGHT = 0;

  @ProtoField(tag = 3, type = INT32)
  public final Integer width;

  @ProtoField(tag = 4, type = INT32)
  public final Integer height;

  public DimensionProto(Integer width, Integer height) {
    this.width = width;
    this.height = height;
  }

  private DimensionProto(Builder builder) {
    this(builder.width, builder.height);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof DimensionProto)) return false;
    DimensionProto o = (DimensionProto) other;
    return equals(width, o.width)
        && equals(height, o.height);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = width != null ? width.hashCode() : 0;
      result = result * 37 + (height != null ? height.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<DimensionProto> {

    public Integer width;
    public Integer height;

    public Builder() {
    }

    public Builder(DimensionProto message) {
      super(message);
      if (message == null) return;
      this.width = message.width;
      this.height = message.height;
    }

    public Builder width(Integer width) {
      this.width = width;
      return this;
    }

    public Builder height(Integer height) {
      this.height = height;
      return this;
    }

    @Override
    public DimensionProto build() {
      return new DimensionProto(this);
    }
  }
}
