// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Purchase.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.STRING;

public final class DirectPurchase extends Message {

  public static final String DEFAULT_DETAILSURL = "";
  public static final String DEFAULT_PURCHASEDOCID = "";
  public static final String DEFAULT_PARENTDOCID = "";
  public static final Integer DEFAULT_OFFERTYPE = 0;

  @ProtoField(tag = 1, type = STRING)
  public final String detailsUrl;

  @ProtoField(tag = 2, type = STRING)
  public final String purchaseDocid;

  @ProtoField(tag = 3, type = STRING)
  public final String parentDocid;

  @ProtoField(tag = 4, type = INT32)
  public final Integer offerType;

  public DirectPurchase(String detailsUrl, String purchaseDocid, String parentDocid, Integer offerType) {
    this.detailsUrl = detailsUrl;
    this.purchaseDocid = purchaseDocid;
    this.parentDocid = parentDocid;
    this.offerType = offerType;
  }

  private DirectPurchase(Builder builder) {
    this(builder.detailsUrl, builder.purchaseDocid, builder.parentDocid, builder.offerType);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof DirectPurchase)) return false;
    DirectPurchase o = (DirectPurchase) other;
    return equals(detailsUrl, o.detailsUrl)
        && equals(purchaseDocid, o.purchaseDocid)
        && equals(parentDocid, o.parentDocid)
        && equals(offerType, o.offerType);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = detailsUrl != null ? detailsUrl.hashCode() : 0;
      result = result * 37 + (purchaseDocid != null ? purchaseDocid.hashCode() : 0);
      result = result * 37 + (parentDocid != null ? parentDocid.hashCode() : 0);
      result = result * 37 + (offerType != null ? offerType.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<DirectPurchase> {

    public String detailsUrl;
    public String purchaseDocid;
    public String parentDocid;
    public Integer offerType;

    public Builder() {
    }

    public Builder(DirectPurchase message) {
      super(message);
      if (message == null) return;
      this.detailsUrl = message.detailsUrl;
      this.purchaseDocid = message.purchaseDocid;
      this.parentDocid = message.parentDocid;
      this.offerType = message.offerType;
    }

    public Builder detailsUrl(String detailsUrl) {
      this.detailsUrl = detailsUrl;
      return this;
    }

    public Builder purchaseDocid(String purchaseDocid) {
      this.purchaseDocid = purchaseDocid;
      return this;
    }

    public Builder parentDocid(String parentDocid) {
      this.parentDocid = parentDocid;
      return this;
    }

    public Builder offerType(Integer offerType) {
      this.offerType = offerType;
      return this;
    }

    @Override
    public DirectPurchase build() {
      return new DirectPurchase(this);
    }
  }
}
