/*
 * Copyright (c) 2014 μg Project Team
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Comment.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.*;

public final class ExternalCommentProto extends Message {

  public static final String DEFAULT_BODY = "";
  public static final Integer DEFAULT_RATING = 0;
  public static final String DEFAULT_CREATORNAME = "";
  public static final Long DEFAULT_CREATIONTIME = 0L;
  public static final String DEFAULT_CREATORID = "";

  @ProtoField(tag = 1, type = STRING)
  public final String body;

  @ProtoField(tag = 2, type = INT32)
  public final Integer rating;

  @ProtoField(tag = 3, type = STRING)
  public final String creatorName;

  @ProtoField(tag = 4, type = INT64)
  public final Long creationTime;

  @ProtoField(tag = 5, type = STRING)
  public final String creatorId;

  public ExternalCommentProto(String body, Integer rating, String creatorName, Long creationTime, String creatorId) {
    this.body = body;
    this.rating = rating;
    this.creatorName = creatorName;
    this.creationTime = creationTime;
    this.creatorId = creatorId;
  }

  private ExternalCommentProto(Builder builder) {
    this(builder.body, builder.rating, builder.creatorName, builder.creationTime, builder.creatorId);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ExternalCommentProto)) return false;
    ExternalCommentProto o = (ExternalCommentProto) other;
    return equals(body, o.body)
        && equals(rating, o.rating)
        && equals(creatorName, o.creatorName)
        && equals(creationTime, o.creationTime)
        && equals(creatorId, o.creatorId);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = body != null ? body.hashCode() : 0;
      result = result * 37 + (rating != null ? rating.hashCode() : 0);
      result = result * 37 + (creatorName != null ? creatorName.hashCode() : 0);
      result = result * 37 + (creationTime != null ? creationTime.hashCode() : 0);
      result = result * 37 + (creatorId != null ? creatorId.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ExternalCommentProto> {

    public String body;
    public Integer rating;
    public String creatorName;
    public Long creationTime;
    public String creatorId;

    public Builder() {
    }

    public Builder(ExternalCommentProto message) {
      super(message);
      if (message == null) return;
      this.body = message.body;
      this.rating = message.rating;
      this.creatorName = message.creatorName;
      this.creationTime = message.creationTime;
      this.creatorId = message.creatorId;
    }

    public Builder body(String body) {
      this.body = body;
      return this;
    }

    public Builder rating(Integer rating) {
      this.rating = rating;
      return this;
    }

    public Builder creatorName(String creatorName) {
      this.creatorName = creatorName;
      return this;
    }

    public Builder creationTime(Long creationTime) {
      this.creationTime = creationTime;
      return this;
    }

    public Builder creatorId(String creatorId) {
      this.creatorId = creatorId;
      return this;
    }

    @Override
    public ExternalCommentProto build() {
      return new ExternalCommentProto(this);
    }
  }
}
