/*
 * Copyright (c) 2014 μg Project Team
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Library.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

public final class LibraryReplicationResponse extends Message {

  public static final List<LibraryUpdate> DEFAULT_UPDATE = Collections.emptyList();

  @ProtoField(tag = 1, label = REPEATED)
  public final List<LibraryUpdate> update;

  public LibraryReplicationResponse(List<LibraryUpdate> update) {
    this.update = immutableCopyOf(update);
  }

  private LibraryReplicationResponse(Builder builder) {
    this(builder.update);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof LibraryReplicationResponse)) return false;
    return equals(update, ((LibraryReplicationResponse) other).update);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = update != null ? update.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<LibraryReplicationResponse> {

    public List<LibraryUpdate> update;

    public Builder() {
    }

    public Builder(LibraryReplicationResponse message) {
      super(message);
      if (message == null) return;
      this.update = copyOf(message.update);
    }

    public Builder update(List<LibraryUpdate> update) {
      this.update = checkForNulls(update);
      return this;
    }

    @Override
    public LibraryReplicationResponse build() {
      return new LibraryReplicationResponse(this);
    }
  }
}
