// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Library.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;

public final class LibraryDirtyData extends Message {

  public static final Integer DEFAULT_BACKEND = 0;

  @ProtoField(tag = 1, type = INT32)
  public final Integer backend;

  public LibraryDirtyData(Integer backend) {
    this.backend = backend;
  }

  private LibraryDirtyData(Builder builder) {
    this(builder.backend);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof LibraryDirtyData)) return false;
    return equals(backend, ((LibraryDirtyData) other).backend);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = backend != null ? backend.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<LibraryDirtyData> {

    public Integer backend;

    public Builder() {
    }

    public Builder(LibraryDirtyData message) {
      super(message);
      if (message == null) return;
      this.backend = message.backend;
    }

    public Builder backend(Integer backend) {
      this.backend = backend;
      return this;
    }

    @Override
    public LibraryDirtyData build() {
      return new LibraryDirtyData(this);
    }
  }
}
