// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Paypal.proto
package com.google.play.proto;

import com.squareup.wire.Message;

public final class PaypalPreapprovalRequestProto extends Message {

  public PaypalPreapprovalRequestProto() {
  }

  private PaypalPreapprovalRequestProto(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof PaypalPreapprovalRequestProto;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<PaypalPreapprovalRequestProto> {

    public Builder() {
    }

    public Builder(PaypalPreapprovalRequestProto message) {
      super(message);
    }

    @Override
    public PaypalPreapprovalRequestProto build() {
      return new PaypalPreapprovalRequestProto(this);
    }
  }
}
