// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/GooglePlus.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class PlusPerson extends Message {

  public static final String DEFAULT_DISPLAYNAME = "";
  public static final String DEFAULT_PROFILEIMAGEURL = "";

  @ProtoField(tag = 2, type = STRING)
  public final String displayName;

  @ProtoField(tag = 4, type = STRING)
  public final String profileImageUrl;

  public PlusPerson(String displayName, String profileImageUrl) {
    this.displayName = displayName;
    this.profileImageUrl = profileImageUrl;
  }

  private PlusPerson(Builder builder) {
    this(builder.displayName, builder.profileImageUrl);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PlusPerson)) return false;
    PlusPerson o = (PlusPerson) other;
    return equals(displayName, o.displayName)
        && equals(profileImageUrl, o.profileImageUrl);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = displayName != null ? displayName.hashCode() : 0;
      result = result * 37 + (profileImageUrl != null ? profileImageUrl.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PlusPerson> {

    public String displayName;
    public String profileImageUrl;

    public Builder() {
    }

    public Builder(PlusPerson message) {
      super(message);
      if (message == null) return;
      this.displayName = message.displayName;
      this.profileImageUrl = message.profileImageUrl;
    }

    public Builder displayName(String displayName) {
      this.displayName = displayName;
      return this;
    }

    public Builder profileImageUrl(String profileImageUrl) {
      this.profileImageUrl = profileImageUrl;
      return this;
    }

    @Override
    public PlusPerson build() {
      return new PlusPerson(this);
    }
  }
}
