// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Purchase.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

public final class PurchaseMetadataResponseProto extends Message {

  @ProtoField(tag = 1)
  public final CountriesProto countries;

  public PurchaseMetadataResponseProto(CountriesProto countries) {
    this.countries = countries;
  }

  private PurchaseMetadataResponseProto(Builder builder) {
    this(builder.countries);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PurchaseMetadataResponseProto)) return false;
    return equals(countries, ((PurchaseMetadataResponseProto) other).countries);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = countries != null ? countries.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<PurchaseMetadataResponseProto> {

    public CountriesProto countries;

    public Builder() {
    }

    public Builder(PurchaseMetadataResponseProto message) {
      super(message);
      if (message == null) return;
      this.countries = message.countries;
    }

    public Builder countries(CountriesProto countries) {
      this.countries = countries;
      return this;
    }

    @Override
    public PurchaseMetadataResponseProto build() {
      return new PurchaseMetadataResponseProto(this);
    }
  }
}
