/*
 * Copyright (c) 2014 μg Project Team
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Unsorted.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

public final class ReconstructDatabaseResponseProto extends Message {

  public static final List<AssetIdentifierProto> DEFAULT_ASSET = Collections.emptyList();

  @ProtoField(tag = 1, label = REPEATED)
  public final List<AssetIdentifierProto> asset;

  public ReconstructDatabaseResponseProto(List<AssetIdentifierProto> asset) {
    this.asset = immutableCopyOf(asset);
  }

  private ReconstructDatabaseResponseProto(Builder builder) {
    this(builder.asset);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ReconstructDatabaseResponseProto)) return false;
    return equals(asset, ((ReconstructDatabaseResponseProto) other).asset);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = asset != null ? asset.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<ReconstructDatabaseResponseProto> {

    public List<AssetIdentifierProto> asset;

    public Builder() {
    }

    public Builder(ReconstructDatabaseResponseProto message) {
      super(message);
      if (message == null) return;
      this.asset = copyOf(message.asset);
    }

    public Builder asset(List<AssetIdentifierProto> asset) {
      this.asset = checkForNulls(asset);
      return this;
    }

    @Override
    public ReconstructDatabaseResponseProto build() {
      return new ReconstructDatabaseResponseProto(this);
    }
  }
}
