// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Offers.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;

public final class RentalTerms extends Message {

  public static final Integer DEFAULT_GRANTPERIODSECONDS = 0;
  public static final Integer DEFAULT_ACTIVATEPERIODSECONDS = 0;

  @ProtoField(tag = 1, type = INT32)
  public final Integer grantPeriodSeconds;

  @ProtoField(tag = 2, type = INT32)
  public final Integer activatePeriodSeconds;

  public RentalTerms(Integer grantPeriodSeconds, Integer activatePeriodSeconds) {
    this.grantPeriodSeconds = grantPeriodSeconds;
    this.activatePeriodSeconds = activatePeriodSeconds;
  }

  private RentalTerms(Builder builder) {
    this(builder.grantPeriodSeconds, builder.activatePeriodSeconds);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RentalTerms)) return false;
    RentalTerms o = (RentalTerms) other;
    return equals(grantPeriodSeconds, o.grantPeriodSeconds)
        && equals(activatePeriodSeconds, o.activatePeriodSeconds);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = grantPeriodSeconds != null ? grantPeriodSeconds.hashCode() : 0;
      result = result * 37 + (activatePeriodSeconds != null ? activatePeriodSeconds.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<RentalTerms> {

    public Integer grantPeriodSeconds;
    public Integer activatePeriodSeconds;

    public Builder() {
    }

    public Builder(RentalTerms message) {
      super(message);
      if (message == null) return;
      this.grantPeriodSeconds = message.grantPeriodSeconds;
      this.activatePeriodSeconds = message.activatePeriodSeconds;
    }

    public Builder grantPeriodSeconds(Integer grantPeriodSeconds) {
      this.grantPeriodSeconds = grantPeriodSeconds;
      return this;
    }

    public Builder activatePeriodSeconds(Integer activatePeriodSeconds) {
      this.activatePeriodSeconds = activatePeriodSeconds;
      return this;
    }

    @Override
    public RentalTerms build() {
      return new RentalTerms(this);
    }
  }
}
