// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Requests.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class RequestSpecificPropertiesProto extends Message {

  public static final String DEFAULT_IFNONEMATCH = "";

  @ProtoField(tag = 1, type = STRING)
  public final String ifNoneMatch;

  public RequestSpecificPropertiesProto(String ifNoneMatch) {
    this.ifNoneMatch = ifNoneMatch;
  }

  private RequestSpecificPropertiesProto(Builder builder) {
    this(builder.ifNoneMatch);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RequestSpecificPropertiesProto)) return false;
    return equals(ifNoneMatch, ((RequestSpecificPropertiesProto) other).ifNoneMatch);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = ifNoneMatch != null ? ifNoneMatch.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<RequestSpecificPropertiesProto> {

    public String ifNoneMatch;

    public Builder() {
    }

    public Builder(RequestSpecificPropertiesProto message) {
      super(message);
      if (message == null) return;
      this.ifNoneMatch = message.ifNoneMatch;
    }

    public Builder ifNoneMatch(String ifNoneMatch) {
      this.ifNoneMatch = ifNoneMatch;
      return this;
    }

    @Override
    public RequestSpecificPropertiesProto build() {
      return new RequestSpecificPropertiesProto(this);
    }
  }
}
