// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Unsorted.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;

public final class SelfUpdateConfig extends Message {

  public static final Integer DEFAULT_LATESTCLIENTVERSIONCODE = 0;

  @ProtoField(tag = 1, type = INT32)
  public final Integer latestClientVersionCode;

  public SelfUpdateConfig(Integer latestClientVersionCode) {
    this.latestClientVersionCode = latestClientVersionCode;
  }

  private SelfUpdateConfig(Builder builder) {
    this(builder.latestClientVersionCode);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof SelfUpdateConfig)) return false;
    return equals(latestClientVersionCode, ((SelfUpdateConfig) other).latestClientVersionCode);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = latestClientVersionCode != null ? latestClientVersionCode.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<SelfUpdateConfig> {

    public Integer latestClientVersionCode;

    public Builder() {
    }

    public Builder(SelfUpdateConfig message) {
      super(message);
      if (message == null) return;
      this.latestClientVersionCode = message.latestClientVersionCode;
    }

    public Builder latestClientVersionCode(Integer latestClientVersionCode) {
      this.latestClientVersionCode = latestClientVersionCode;
      return this;
    }

    @Override
    public SelfUpdateConfig build() {
      return new SelfUpdateConfig(this);
    }
  }
}
