// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Debug.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.DOUBLE;
import static com.squareup.wire.Message.Datatype.STRING;

public final class TimingProto extends Message {

  public static final String DEFAULT_NAME = "";
  public static final Double DEFAULT_TIMEINMS = 0D;

  @ProtoField(tag = 3, type = STRING)
  public final String name;

  @ProtoField(tag = 4, type = DOUBLE)
  public final Double timeInMs;

  public TimingProto(String name, Double timeInMs) {
    this.name = name;
    this.timeInMs = timeInMs;
  }

  private TimingProto(Builder builder) {
    this(builder.name, builder.timeInMs);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof TimingProto)) return false;
    TimingProto o = (TimingProto) other;
    return equals(name, o.name)
        && equals(timeInMs, o.timeInMs);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = name != null ? name.hashCode() : 0;
      result = result * 37 + (timeInMs != null ? timeInMs.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<TimingProto> {

    public String name;
    public Double timeInMs;

    public Builder() {
    }

    public Builder(TimingProto message) {
      super(message);
      if (message == null) return;
      this.name = message.name;
      this.timeInMs = message.timeInMs;
    }

    public Builder name(String name) {
      this.name = name;
      return this;
    }

    public Builder timeInMs(Double timeInMs) {
      this.timeInMs = timeInMs;
      return this;
    }

    @Override
    public TimingProto build() {
      return new TimingProto(this);
    }
  }
}
