// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Unsorted.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.BOOL;

public final class UserSettings extends Message {

  public static final Boolean DEFAULT_TOSCHECKBOXMARKETINGEMAILSOPTEDIN = false;

  @ProtoField(tag = 1, type = BOOL)
  public final Boolean tosCheckboxMarketingEmailsOptedIn;

  public UserSettings(Boolean tosCheckboxMarketingEmailsOptedIn) {
    this.tosCheckboxMarketingEmailsOptedIn = tosCheckboxMarketingEmailsOptedIn;
  }

  private UserSettings(Builder builder) {
    this(builder.tosCheckboxMarketingEmailsOptedIn);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof UserSettings)) return false;
    return equals(tosCheckboxMarketingEmailsOptedIn, ((UserSettings) other).tosCheckboxMarketingEmailsOptedIn);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = tosCheckboxMarketingEmailsOptedIn != null ? tosCheckboxMarketingEmailsOptedIn.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<UserSettings> {

    public Boolean tosCheckboxMarketingEmailsOptedIn;

    public Builder() {
    }

    public Builder(UserSettings message) {
      super(message);
      if (message == null) return;
      this.tosCheckboxMarketingEmailsOptedIn = message.tosCheckboxMarketingEmailsOptedIn;
    }

    public Builder tosCheckboxMarketingEmailsOptedIn(Boolean tosCheckboxMarketingEmailsOptedIn) {
      this.tosCheckboxMarketingEmailsOptedIn = tosCheckboxMarketingEmailsOptedIn;
      return this;
    }

    @Override
    public UserSettings build() {
      return new UserSettings(this);
    }
  }
}
