// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/Unsorted.proto
package com.google.play.proto;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;

public final class VerifyAssociationResponse extends Message {

  public static final Integer DEFAULT_STATUS = 0;

  @ProtoField(tag = 1, type = INT32)
  public final Integer status;

  @ProtoField(tag = 2)
  public final Address billingAddress;

  @ProtoField(tag = 3)
  public final CarrierTos carrierTos;

  public VerifyAssociationResponse(Integer status, Address billingAddress, CarrierTos carrierTos) {
    this.status = status;
    this.billingAddress = billingAddress;
    this.carrierTos = carrierTos;
  }

  private VerifyAssociationResponse(Builder builder) {
    this(builder.status, builder.billingAddress, builder.carrierTos);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof VerifyAssociationResponse)) return false;
    VerifyAssociationResponse o = (VerifyAssociationResponse) other;
    return equals(status, o.status)
        && equals(billingAddress, o.billingAddress)
        && equals(carrierTos, o.carrierTos);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = status != null ? status.hashCode() : 0;
      result = result * 37 + (billingAddress != null ? billingAddress.hashCode() : 0);
      result = result * 37 + (carrierTos != null ? carrierTos.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<VerifyAssociationResponse> {

    public Integer status;
    public Address billingAddress;
    public CarrierTos carrierTos;

    public Builder() {
    }

    public Builder(VerifyAssociationResponse message) {
      super(message);
      if (message == null) return;
      this.status = message.status;
      this.billingAddress = message.billingAddress;
      this.carrierTos = message.carrierTos;
    }

    public Builder status(Integer status) {
      this.status = status;
      return this;
    }

    public Builder billingAddress(Address billingAddress) {
      this.billingAddress = billingAddress;
      return this;
    }

    public Builder carrierTos(CarrierTos carrierTos) {
      this.carrierTos = carrierTos;
      return this;
    }

    @Override
    public VerifyAssociationResponse build() {
      return new VerifyAssociationResponse(this);
    }
  }
}
